# Generated by Django 4.2.13 on 2024-06-08 07:39

from django.db import migrations
import imagekit.models.fields
import post.models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0007_auto_20190928_0008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="photo",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to=post.models.photo_path
            ),
        ),
    ]
