# Generated by Django 3.2.21 on 2024-06-12 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_question_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='liked_by',
        ),
    ]
